name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치로 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}  # GitHub Secrets에 개인 SSH 키 저장

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@your-ec2-public-ip << 'EOF'
            cd /var/www/your-project-directory
            git pull origin main
            sudo systemctl restart nginx  # 필요 시, 웹 서버 재시작
          EOF
